### ISSUE TITLE
Make an inline demo

### ISSUE THREAD

**Issue by dlockhart** [BrightspaceUI/tile#25]
webcomponents.org supports inline demos now, we should add some!

**Comment by dbatiste** [comment]
See [d2l-alert](https://www.webcomponents.org/element/BrightspaceUI/alert) on webcomponents.org as an example.  As Dave mentioned, it enables live editing of the demo with is super cool/handy.  

I am planning to go through our other components and update in the next couple of weeks.  I may forgo the screenshot entirely since it's a pain to maintain, and sort of becomes redundant in the webcomponents.org context.  The downside to that is that we lose the visual representation in the GitHub context.  FYI: It is possible to preview as well, so it's not necessary to release/publish to see the snippet in action.

The snippet is added to the readme as a comment.  See [raw d2l-alert readme](https://raw.githubusercontent.com/BrightspaceUI/alert/master/README.md) as example.

**Comment by jstefaniuk-d2l** [comment]
Right now the site reads:

```
Error 404 - -1
Could not find element
```

Does something need to be done before this can be worked on?

**Comment by dbatiste** [comment]
Should be able to preview.  It does some code mirroring and caching.  I can take a look shortly if still trouble.  Here's another sample (pointing to branch) that I've been working on: https://www.webcomponents.org/preview/BrightspaceUI/button-group/d0c7bf2b3fe3e165c171921348e44ce7ecb0f437

**Comment by jstefaniuk-d2l** [comment]
Found it, thanks!
