### ISSUE TITLE
Work to support the "My Courses" d2l-course-tile

### ISSUE THREAD

**Issue by jstefaniuk-d2l** [BrightspaceUI/tile#40]
Let's utilize the d2l-image-tile in our most famous tile

TODO:
- ~~The slotted content should be aware of whether the tile is hovered (so it can be underlined)~~ should hopefully be simple css
- ~~Any work that needs to be done to support the longpress menu~~ (I think this can be handled by the consumer)

Done:
- Ported over the hover effects
- Add a mechanism to slot menu-adjacent content https://github.com/BrightspaceUI/tile/pull/43
- Add an option for the `...` menu to not always show if the user is on a touch device https://github.com/BrightspaceUI/tile/pull/44

**Comment by dlockhart** [comment]
Cool! So the "Polymer 2" way to do this kind of stuff is going to rely heavily on class extensions. So you'd make say a "course tile" that extends "tile" and "image-tile" and maybe "pinnable-tile". Instead of the primitive "tile" class knowing about images and pinning, it will just contain a bunch of slots for all the things it can imagine to plug in. This is how mixins are going to work in Polymer 2 as well.

Just keep that in the back of your mind while you implement.

**Comment by jstefaniuk-d2l** [comment]
Work should be all done! Any further work we find is needed to support the course tile can be separate issues
